author: Luke Closs <test-mock-lwp@awesnob.com>
build_requires: 
  Test::More: 0.42
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Test-Mock-LWP
no_index: 
  directory: 
    - inc
    - t
